version: '3.3'

services:

  mongo:
    container_name: gist-clone-mongo
    image: mongo:6.0.3
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
